import { appSchema, tableSchema } from '@nozbe/watermelondb'

export const mySchema = appSchema({
  version: 9,
  tables: [
    tableSchema({
      name: 'incidents',
      columns: [
        // Core fields
        { name: 'installation_id', type: 'number', isIndexed: true },
        { name: 'asset_id', type: 'number', isOptional: true },
        { name: 'reporter_username', type: 'string' },
        { name: 'note', type: 'string' },
        { name: 'time_adjustment_seconds', type: 'number' },
        { name: 'severity', type: 'string' },
        { name: 'source', type: 'string' },
        { name: 'created_at', type: 'number' },
        // Legacy sync fields (keep for compatibility)
        { name: 'is_synced', type: 'boolean', isIndexed: true },
        { name: 'remote_id', type: 'number', isOptional: true, isIndexed: true },
        // Offline sync v2
        { name: 'local_id', type: 'string', isIndexed: true },
        { name: 'remote_installation_id', type: 'number', isOptional: true },
        { name: 'local_case_local_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string', isIndexed: true }, // pending|syncing|failed|synced
        { name: 'sync_attempts', type: 'number' },
        { name: 'last_sync_error', type: 'string', isOptional: true },
        { name: 'client_request_id', type: 'string' },
        { name: 'gps_capture_status', type: 'string' },
        { name: 'gps_capture_source', type: 'string' },
        { name: 'gps_lat', type: 'number', isOptional: true },
        { name: 'gps_lng', type: 'number', isOptional: true },
        { name: 'gps_accuracy_m', type: 'number', isOptional: true },
        { name: 'gps_captured_at', type: 'string', isOptional: true },
        { name: 'gps_capture_note', type: 'string' },
        { name: 'incident_status', type: 'string' },
        { name: 'status_updated_at', type: 'string', isOptional: true },
        { name: 'status_updated_by', type: 'string', isOptional: true },
        { name: 'estimated_duration_seconds', type: 'number', isOptional: true },
        { name: 'work_started_at', type: 'string', isOptional: true },
        { name: 'work_ended_at', type: 'string', isOptional: true },
        { name: 'actual_duration_seconds', type: 'number', isOptional: true },
        { name: 'resolved_at', type: 'string', isOptional: true },
        { name: 'resolved_by', type: 'string', isOptional: true },
        { name: 'resolution_note', type: 'string', isOptional: true },
        { name: 'target_lat', type: 'number', isOptional: true },
        { name: 'target_lng', type: 'number', isOptional: true },
        { name: 'target_label', type: 'string', isOptional: true },
        { name: 'target_source', type: 'string', isOptional: true },
        { name: 'target_updated_at', type: 'string', isOptional: true },
        { name: 'target_updated_by', type: 'string', isOptional: true },
        { name: 'dispatch_required', type: 'boolean' },
        { name: 'dispatch_place_name', type: 'string', isOptional: true },
        { name: 'dispatch_address', type: 'string', isOptional: true },
        { name: 'dispatch_reference', type: 'string', isOptional: true },
        { name: 'dispatch_contact_name', type: 'string', isOptional: true },
        { name: 'dispatch_contact_phone', type: 'string', isOptional: true },
        { name: 'dispatch_notes', type: 'string', isOptional: true },
        { name: 'checklist_items_json', type: 'string', isOptional: true },
        { name: 'evidence_note', type: 'string', isOptional: true },
        // Legacy column kept only for on-device schema compatibility during upgrades.
        { name: 'geofence_override_note', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'photos',
      columns: [
        // Core fields
        { name: 'incident_id', type: 'string', isIndexed: true },
        { name: 'r2_key', type: 'string', isOptional: true },
        { name: 'file_name', type: 'string' },
        { name: 'content_type', type: 'string' },
        { name: 'size_bytes', type: 'number' },
        { name: 'sha256', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        // Legacy sync fields
        { name: 'is_synced', type: 'boolean', isIndexed: true },
        { name: 'local_path', type: 'string' },
        { name: 'remote_id', type: 'number', isOptional: true, isIndexed: true },
        // Offline sync v2
        { name: 'local_id', type: 'string' },
        { name: 'remote_photo_id', type: 'number', isOptional: true },
        { name: 'remote_incident_id', type: 'number', isOptional: true },
        { name: 'local_incident_local_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'sync_attempts', type: 'number' },
        { name: 'last_sync_error', type: 'string', isOptional: true },
        { name: 'client_request_id', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'sync_jobs',
      columns: [
        { name: 'entity_type', type: 'string' },       // case|incident|incident_evidence|photo
        { name: 'entity_local_id', type: 'string', isIndexed: true },
        { name: 'operation', type: 'string' },          // create_incident|upload_photo|etc
        { name: 'depends_on_job_id', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true }, // pending|syncing|failed|synced
        { name: 'attempt_count', type: 'number' },
        { name: 'next_retry_at', type: 'number' },      // epoch ms; 0 = run immediately
        { name: 'last_error', type: 'string', isOptional: true },
        { name: 'priority', type: 'number' },           // lower = higher priority
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    // Stub for phase 3 (case manual offline)
    tableSchema({
      name: 'cases_local',
      columns: [
        { name: 'local_id', type: 'string', isIndexed: true },
        { name: 'remote_id', type: 'number', isOptional: true },
        { name: 'client_name', type: 'string' },
        { name: 'notes', type: 'string' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'sync_attempts', type: 'number' },
        { name: 'last_sync_error', type: 'string', isOptional: true },
        { name: 'client_request_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'assigned_incidents_map_cache',
      columns: [
        { name: 'incident_remote_id', type: 'number', isIndexed: true },
        { name: 'installation_id', type: 'number', isIndexed: true },
        { name: 'asset_id', type: 'number', isOptional: true },
        { name: 'severity', type: 'string' },
        { name: 'incident_status', type: 'string', isIndexed: true },
        { name: 'created_at_iso', type: 'string' },
        { name: 'target_lat', type: 'number', isOptional: true },
        { name: 'target_lng', type: 'number', isOptional: true },
        { name: 'target_label', type: 'string', isOptional: true },
        { name: 'dispatch_place_name', type: 'string', isOptional: true },
        { name: 'dispatch_address', type: 'string', isOptional: true },
        { name: 'dispatch_reference', type: 'string', isOptional: true },
        { name: 'dispatch_contact_name', type: 'string', isOptional: true },
        { name: 'dispatch_contact_phone', type: 'string', isOptional: true },
        { name: 'dispatch_notes', type: 'string', isOptional: true },
        { name: 'installation_client_name', type: 'string', isOptional: true },
        { name: 'installation_label', type: 'string', isOptional: true },
        { name: 'asset_code', type: 'string', isOptional: true },
        { name: 'assignment_role', type: 'string', isOptional: true },
        { name: 'assignment_source', type: 'string', isOptional: true },
        { name: 'assigned_at', type: 'string', isOptional: true },
        { name: 'cached_at', type: 'number', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'technician_assignments_cache',
      columns: [
        { name: 'technician_id', type: 'number', isIndexed: true },
        { name: 'tenant_id', type: 'string' },
        { name: 'entity_type', type: 'string', isIndexed: true },
        { name: 'entity_id', type: 'string', isIndexed: true },
        { name: 'assignment_role', type: 'string' },
        { name: 'assigned_by_user_id', type: 'number', isOptional: true },
        { name: 'assigned_by_username', type: 'string', isOptional: true },
        { name: 'assigned_at', type: 'string', isOptional: true },
        { name: 'unassigned_at', type: 'string', isOptional: true },
        { name: 'metadata_json', type: 'string', isOptional: true },
        { name: 'technician_display_name', type: 'string', isOptional: true },
        { name: 'technician_employee_code', type: 'string', isOptional: true },
        { name: 'technician_is_active', type: 'boolean', isOptional: true },
        { name: 'cached_at', type: 'number', isIndexed: true },
      ],
    }),
  ],
})
